Table configuraciones {
    id int [pk, increment] // Primary key
    nombre varchar
    descripcion varchar
    direccion varchar
    telefono varchar
    divisa varchar
    correo_electronico varchar
    web varchar
    logo varchar
}

Table gestiones {
    id int [pk, increment] // Primary key
    nombre varchar
}

Table periodos {
    id int [pk, increment] // Primary key
    nombre varchar
    gestion_id int [ref: > gestiones.id]
}

Table niveles {
    id int [pk, increment] // Primary key
    nombre varchar
}

Table grados {
    id int [pk, increment] // Primary key
    nombre varchar
    nivel_id int [ref: > niveles.id]
}

Table paralelos {
    id int [pk, increment] // Primary key
    nombre varchar
    grado_id int [ref: > grados.id]
}

Table turnos {
    id int [pk, increment] // Primary key
    nombre varchar
}

Table materias {
    id int [pk, increment] // Primary key
    nombre varchar
}

Table users {
    id int [pk, increment] // Primary key
    name varchar
    email varchar
    password varchar
}

Table personals {
    id int [pk, increment] // Primary key
    usuario_id int [ref: > users.id]
    tipo varchar
    nombres varchar
    apellidos varchar
    ci varchar
    fecha_nacimiento date
    direccion varchar
    telefono varchar
    profesion varchar
    foto varchar
}

Table formaciones {
    id int [pk, increment] // Primary key
    personal_id int [ref: > personals.id]
    titulo varchar
    institucion varchar
    nivel varchar
    ano_graduacion varchar
    archivo varchar
}

Table ppffs {
    id int [pk, increment] // Primary key
    nombres varchar
    apellidos varchar
    ci varchar
    fecha_nacimiento date
    telefono varchar
    parentesco varchar
    ocupacion varchar
    direccion varchar
}

Table estudiantes {
    id int [pk, increment] // Primary key
    usuario_id int [ref: > users.id]
    ppff_id int [ref: > ppffs.id]
    nombres varchar
    apellidos varchar
    ci varchar
    fecha_nacimiento date
    direccion varchar
    telefono varchar
    foto varchar
    estado varchar
}